### PR TITLE
Fixed output regex and modified C++ code to output ctrl-a at the end …

### PR DESCRIPTION
**Pull request by sshivaji**
…of find output for easy tracing

Solution was to put a ctrl-a character at the end of the find command output. chess_db.py and test.py have all been updated to make it work.

### CODE REVIEW

**Comment by mcostalba** [comment]
Can you please use something like:

```
    def find(self, fen, max_offsets=10):
        '''Find all games with positions equal to fen'''
        if not self.db or not self.p:
            raise NameError("Unknown DB, first open a PGN file")
        cmd = "find {} max_game_offsets {} {}".format(self.db, max_offsets, fen)
        self.p.sendline(cmd)
        result = ''
        while True:
            self.p.expect(FIND_OUTPUT_REGEX)
            result += self.p.before + "}"
            self.p.before = ''
            if result.count('{') == result.count('}'):
                break
        return json.loads(result)

It seems less hacky to me, moreover we stick to output regular JSON in the C++ tool.

```

**Comment by gbtami** [comment]
I think it would be more elegant to follow the scoutfish way to solve this issue using UCI "isready" and "readyok".

**Comment by mcostalba** [comment]
@gbtami yes, I agree. This is by far the best way. But it requires to add UCI command loop to chess_db, as is in scoutfih. Anyhow this is the way to go.

**Comment by sshivaji** [comment]
Will test out the solution above until uci command loop is available

**Comment by sshivaji** [comment]
@mcostalba, tried that solution. Unfortunately, its not that simple. I am running into eof issues and more. I agree that uci readyok is the right solution.

However, for now, another solution that works is to simply put in 2 new lines at the end of the JSON ie (\n,\n,\n). That works well in the regex and in chessui as well. Would that be acceptable?

**Comment by sshivaji** [comment]
One idea is that I will try out the best solution (maybe tabs before and after the last closing brace) that should pass the following tests:

1. A "naked" command line JSON parse call from python (or other languages).
2. Works well with chess_db.
3. Works well for long UI sequences with chessui.

Will see if I can improve over 2 \n and post back.

**Comment by mcostalba** [comment]
It should be fixed now. Closing this.

**Pull request closed without merging**
